const getImageSrc = (imagePath: string | null) => {
  const images: { [key: string]: any } = {
    "nutri_feast.jpg": require("@/assets/images/restaurants/nutri_feast.jpg"),
    "healthy_bites.jpg": require("@/assets/images/restaurants/healthy_bites.jpg"),
    "fit_fuel.jpg": require("@/assets/images/restaurants/fit_fuel.jpg"),
    "gains_grill.jpg": require("@/assets/images/restaurants/gains_grill.jpg"),
    "lean_kitchen.jpg": require("@/assets/images/restaurants/lean_kitchen.jpg"),
    "protein_palace.jpg": require("@/assets/images/restaurants/protein_palace.jpg"),
    "muscle_meals.jpg": require("@/assets/images/restaurants/muscle_meals.jpg"),
    "calorie_cutters.jpg": require("@/assets/images/restaurants/calorie_cutters.jpg"),
    "shred_cafe.jpg": require("@/assets/images/restaurants/shred_cafe.jpg"),
    "balanced_bowls.jpg": require("@/assets/images/restaurants/balanced_bowls.jpg"),
    "salads.jpg": require("@/assets/images/categories/salads.jpg"),
    "wraps_and_sandwiches.jpg": require("@/assets/images/categories/wraps_and_sandwiches.jpg"),
    "rice_and_grain_bowls.jpg": require("@/assets/images/categories/rice_and_grain_bowls.jpg"),
    "smoothies_and_shakes.jpg": require("@/assets/images/categories/smoothies_and_shakes.jpg"),
    "breakfast_and_pancakes.jpg": require("@/assets/images/categories/breakfast_and_pancakes.jpg"),
    "high-protein_meals.jpg": require("@/assets/images/categories/high-protein_meals.jpg"),
    "vegetarian_and_vegan.jpg": require("@/assets/images/categories/vegetarian_and_vegan.jpg"),
    "seafood.jpg": require("@/assets/images/categories/seafood.jpg"),
    "healthy_snacks.jpg": require("@/assets/images/categories/healthy_snacks.jpg"),
    "almond_butter_oatmeal.jpg": require("@/assets/images/foods/almond_butter_oatmeal.jpg"),
    "avocado_toast.jpg": require("@/assets/images/foods/avocado_toast.jpg"),
    "baked_salmon_asparagus.jpg": require("@/assets/images/foods/baked_salmon_asparagus.jpg"),
    "baked_sweet_potato_fries.jpg": require("@/assets/images/foods/baked_sweet_potato_fries.jpg"),
    "banana_protein_shake.jpg": require("@/assets/images/foods/banana_protein_shake.jpg"),
    "beef_stir_fry.jpg": require("@/assets/images/foods/beef_stir_fry.jpg"),
    "brown_rice_chicken.jpg": require("@/assets/images/foods/brown_rice_chicken.jpg"),
    "chia_pudding.jpg": require("@/assets/images/foods/chia_pudding.jpg"),
    "chicken_alfredo.jpg": require("@/assets/images/foods/chicken_alfredo.jpg"),
    "chicken_avocado_wrap.jpg": require("@/assets/images/foods/chicken_avocado_wrap.jpg"),
    "chicken_rice.jpg": require("@/assets/images/foods/chicken_rice.jpg"),
    "chocolate_protein_shake.jpg": require("@/assets/images/foods/chocolate_protein_shake.jpg"),
    "cottage_cheese_pancakes.jpg": require("@/assets/images/foods/cottage_cheese_pancakes.jpg"),
    "egg_avocado_toast.jpg": require("@/assets/images/foods/egg_avocado_toast.jpg"),
    "egg_oats.jpg": require("@/assets/images/foods/egg_oats.jpg"),
    "egg_turkey_bacon.jpg": require("@/assets/images/foods/egg_turkey_bacon.jpg"),
    "egg_white_omelette.jpg": require("@/assets/images/foods/egg_white_omelette.jpg"),
    "greek_yogurt_parfait.jpg": require("@/assets/images/foods/greek_yogurt_parfait.jpg"),
    "grilled_chicken_breast.jpg": require("@/assets/images/foods/grilled_chicken_breast.jpg"),
    "grilled_chicken_caesar_salad.jpg": require("@/assets/images/foods/grilled_chicken_caesar_salad.jpg"),
    "grilled_shrimp_quinoa.jpg": require("@/assets/images/foods/grilled_shrimp_quinoa.jpg"),
    "grilled-chicken-salad.jpg": require("@/assets/images/foods/grilled-chicken-salad.jpg"),
    "high_protein_pancakes.jpg": require("@/assets/images/foods/high_protein_pancakes.jpg"),
    "kale_chicken_caesar.jpg": require("@/assets/images/foods/kale_chicken_caesar.jpg"),
    "lean_beef_burger.jpg": require("@/assets/images/foods/lean_beef_burger.jpg"),
    "lean_beef_rice_bowl.jpg": require("@/assets/images/foods/lean_beef_rice_bowl.jpg"),
    "lean_meatballs_quinoa.jpg": require("@/assets/images/foods/lean_meatballs_quinoa.jpg"),
    "lean_turkey_rice.jpg": require("@/assets/images/foods/lean_turkey_rice.jpg"),
    "mango_protein_shake.jpg": require("@/assets/images/foods/mango_protein_shake.jpg"),
    "oatmeal_almonds.jpg": require("@/assets/images/foods/oatmeal_almonds.jpg"),
    "protein_brownie.jpg": require("@/assets/images/foods/protein_brownie.jpg"),
    "protein_oatmeal.jpg": require("@/assets/images/foods/protein_oatmeal.jpg"),
    "protein_smoothie.jpg": require("@/assets/images/foods/protein_smoothie.jpg"),
    "protein_waffles.jpg": require("@/assets/images/foods/protein_waffles.jpg"),
    "quinoa_black_bean_bowl.jpg": require("@/assets/images/foods/quinoa_black_bean_bowl.jpg"),
    "quinoa_power_bowl.jpg": require("@/assets/images/foods/quinoa_power_bowl.jpg"),
    "salad_grilled_tofu.jpg": require("@/assets/images/foods/salad_grilled_tofu.jpg"),
    "salmon_avocado_bowl.jpg": require("@/assets/images/foods/salmon_avocado_bowl.jpg"),
    "salmon_bowl.jpg": require("@/assets/images/foods/salmon_bowl.jpg"),
    "salmon_broccoli.jpg": require("@/assets/images/foods/salmon_broccoli.jpg"),
    "spicy_chickpea_wrap.jpg": require("@/assets/images/foods/spicy_chickpea_wrap.jpg"),
    "steak_sweet_potato.jpg": require("@/assets/images/foods/steak_sweet_potato.jpg"),
    "steamed_fish_rice.jpg": require("@/assets/images/foods/steamed_fish_rice.jpg"),
    "tofu_buddha_bowl.jpg": require("@/assets/images/foods/tofu_buddha_bowl.jpg"),
    "tofu_stir_fry.jpg": require("@/assets/images/foods/tofu_stir_fry.jpg"),
    "tuna_avocado_wrap.jpg": require("@/assets/images/foods/tuna_avocado_wrap.jpg"),
    "turkey_wrap.jpg": require("@/assets/images/foods/turkey_wrap.jpg"),
    "vegan_protein_smoothie.jpg": require("@/assets/images/foods/vegan_protein_smoothie.jpg"),
    "veggie_wrap.jpg": require("@/assets/images/foods/veggie_wrap.jpg"),
    "zucchini_noodles_chicken.jpg": require("@/assets/images/foods/zucchini_noodles_chicken.jpg"),
  };

  if (!imagePath) return null;

  const filename = imagePath.split("/").pop();

  return filename
    ? images[filename] || require("@/assets/images/default.jpg")
    : require("@/assets/images/default.jpg");
};

export default getImageSrc;
